experiment_name: "baseline_model"

paths:
  data_path: "data/raw/ml-10M100K/ratings.dat"   # DVC-tracked file
  models_dir: "models"
  logs_dir: "logs"                      # optional, in case you want it later

training:
  random_seed: 42
  test_size: 0.2

github_repo: "ADS2025-A2/team-A2-recsys"
DB_NAME : "src/app/user_data.db"

models:
  bpr:
    class_name: "SpotlightBPRRecommender"
    params: 
      embedding_dim: 32
      n_iter: 10
      batch_size: 2048
      learning_rate: 0.001
      l2: 1e-6
      num_negative_samples: 3
      use_cuda: false

  adaptive:
    class_name: "SpotlightAdaptiveRecommender"
    params:
      embedding_dim: 16
      n_iter: 10
      batch_size: 2048
      learning_rate: 0.005
      l2: 1e-6
      num_negative_samples: 5
      use_cuda: false

primary_model_key: "bpr"